---
- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: update index repo
      package:
        update_cache: yes

- hosts: Apache
  gather_facts: no
  become: true
  roles:
    - Apache

- hosts: Docker
  gather_facts: no
  become: true
  roles:
    - Docker

- hosts: Terraform
  gather_facts: no
  become: true
  roles:
    - Terraform

- hosts: Jenkins
  gather_facts: no
  become: true
  roles:
    - Jenkins
